name = "tg-bot-panel"
main = "src/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = [ "nodejs_compat" ]

[[kv_namespaces]]
binding = "DB"
id = "PLACEHOLDER" 

[[kv_namespaces]]
binding = "STATE"
id = "PLACEHOLDER"
